export default {
  MAX_REPAIR_HITS: 250000,
  MAX_CONSTRUCTION_SITES: 5,
  MAX_TOWER_REFILL: 500,
  ticks: {
    SPAWN_CREEPS: 10,
    RECHECK_TASK_VALIDITY: 5,
    DELETE_DEAD_CREEP_MEMORY: 5,
    PLAN_ROOMS: 69
  }
};
